DAY_TYPE_HOLIDAY = "holiday"
DAY_TYPE_WEEKEND = "saturday"
DAY_TYPE_WEEKDAY = "weekday"

VALID_DAY_TYPES = [
    DAY_TYPE_HOLIDAY,
    DAY_TYPE_WEEKEND,
    DAY_TYPE_WEEKDAY,
]

CACHE_DIR = "cache_directory"